# Generated by Django 4.2.4 on 2023-09-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='cuerpo',
            field=models.CharField(default='Cuerpo Reseña', max_length=3000),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
