# Generated by Django 4.2.4 on 2023-09-01 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_reseña_cuerpo_alter_reseña_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='autor',
            field=models.CharField(default='Autor Reseña', max_length=20),
        ),
        migrations.AddField(
            model_name='reseña',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
