# Generated by Django 4.2.4 on 2023-09-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_reseña_autor_reseña_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='cuerpo',
            field=models.CharField(default='Cuerpo Reseña', max_length=1000),
        ),
    ]
