# Generated by Django 4.2.4 on 2023-09-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_avatar_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=20),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='cuerpo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='imagen',
            field=models.ImageField(upload_to='portadas'),
        ),
    ]
