# Generated by Django 4.2.4 on 2023-09-03 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0010_alter_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='decripcion',
        ),
        migrations.RemoveField(
            model_name='data',
            name='weblink',
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
