# Generated by Django 4.2.4 on 2023-09-03 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0011_remove_data_decripcion_remove_data_weblink_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Avatar',
        ),
    ]
