# Generated by Django 4.2.4 on 2023-09-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_alter_avatar_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
