# Generated by Django 4.2.4 on 2023-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMail', '0002_mensajes_delete_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='asunto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
