# Generated by Django 4.2.4 on 2023-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMail', '0003_mensajes_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
