# Generated by Django 4.2.4 on 2023-09-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMail', '0006_mensajes_estado_alter_mensajes_leido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='leido',
        ),
    ]
